config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
    resources :comments, only: [:create, :destroy]
  end
  resources :profile, only: [:show]

  devise_for :users, controllers: { registrations: "users_controllers/registrations" }

  get 'blogs/user/:user_id', to: 'blogs#index', as: 'user_blogs'

  root to: "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: { in: 5..40 }
  validates :text, presence: true

  def created_at_h
    created_at.strftime("%d %b. %Y %H:%M")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs
  has_many :comments

  enum role: {
    user: 'user',
    editor: 'editor',
    admin: 'admin'
  }

  #validates :role, inclusion_of: ROLES

  mount_uploader :photo, PhotoUploader

  #ROLES = %w(user admin editor)

  def get_username
    "#{name} #{surname}"
  end

  def created_at_h
    created_at.strftime("%d/%m/%Y %H:%M")
  end

  def current_user?(user_id)
    id == user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  private

    def user_not_authorized
      flash[:warning] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end

    def render_404
      render :template => "errors/404", :status => 404
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  expose_decorated :blog
  expose_decorated :blogs, -> {fetch_blogs}

  expose_decorated :comment, -> {Comment.new}

  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def new
    authorize blog
  end

  def create
    blog.user_id = current_user.id
    if blog.save
      redirect_to blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize blog
  end

  def update
    if blog.update(blog_params)
      redirect_to blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize blog

    blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private
    def fetch_blogs
      blogs = Blog.all
      blogs = Blog.where(user_id: params[:user_id]).order(:created_at) if params[:user_id]
      blogs
    end

    def blog_params
      params.require(:blog).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose_decorated :comment
  expose_decorated :comments, -> {fetch_comments}

  before_action :authenticate_user!

  def create
    authorize comment
    comment.save
    redirect_to :back
  end

  def destroy
    authorize comment
    comment.destroy
    redirect_to :back, notice: 'Comment was successfully destroyed.'
  end

  private

    def fetch_comments
      comments = Comment.all
    end

    def comment_params
      params.require(:comment).permit(:user_id, :blog_id, :text)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  expose_decorated :user
end

app/controllers/users_controllers/confirmations_controller.rb
class UsersControllers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users_controllers/omniauth_callbacks_controller.rb
class UsersControllers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users_controllers/passwords_controller.rb
class UsersControllers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users_controllers/registrations_controller.rb
class UsersControllers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :date_of_birth, :photo])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :date_of_birth, :photo, :role])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controllers/sessions_controller.rb
class UsersControllers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controllers/unlocks_controller.rb
class UsersControllers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/application/_navigation.html.slim
.top-bar
  .top-bar-left
    ul class="dropdown menu" data-dropdown-menu=true
      li class="menu-text"
        Site title
      li = link_to "Home", root_path
      li = link_to "Create blog", new_blog_path
  .top-bat-right
    ul class="menu"
      - if user_signed_in?
        li = link_to current_user.get_username, profile_path(current_user)
        li = link_to "Exit", destroy_user_session_path, method: :delete if user_signed_in?
      - else
        li
          = link_to "Sign in", new_user_session_path
        li
          = link_to "Sign up", new_user_registration_path

app/views/blogs/_form.html.slim
= simple_form_for blog do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, as: :string
    = f.input :text, as: :text

  .form-actions
    br
    = f.button :submit, class:"button small success"


script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"
script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.0/js/froala_editor.pkgd.min.js"

script $(function() { $('textarea').froalaEditor() });

app/views/blogs/_links.html.slim
- if action_name == 'show'
  - if (user_signed_in? && (current_user == blog.user || current_user.admin? || current_user.editor?))
      = link_to 'Edit', edit_blog_path(blog), class:"button tiny success"
      '
      = link_to 'Delete', blog_path(blog), method: :delete, data: {confirm: "Are you sure?"}, class:"button tiny alert"
      '
      = link_to 'Back', blogs_path, class:"button tiny"

- if action_name == 'edit'
  = link_to 'Show', blog, class:"button tiny"

app/views/blogs/edit.html.slim
- content_for :title, "Blog editing"

.medium-10.medium-centered.column style="padding-top: 5%;"
  .callout
    h1 Editing Blog

    = render 'form', blog: blog

    = render 'links'

app/views/blogs/index.html.slim
- content_for :title, "Blogs"
p
  #notice
    = notice
- if blogs.count == 0
  .emty-list.medium-12.text-center
    h4 While there is nothing here
    span
      | You can
      '
      = link_to "add", new_blog_path
      '    the your first blog!
- blogs.each do |blog|
  .blog
    .medium-10.medium-centered.column
      .callout
        .title
          .float-left
            h5 = link_to blog.title, blog_path(blog.id)
            h6.subheader.author = link_to blog.user.get_username, profile_path(blog.user)
          .float-right
            = blog.created_at_h
        br
        .text style="padding-top: 20px;"
        = raw blog.text

        .comments-count
          = " #{blog.comments_count} comments"

app/views/blogs/new.html.slim
- content_for :title, "Blog creating"

.medium-10.medium-centered.column style="padding-top: 5%;"
    .callout
        h1 New Blog

        = render 'form', blog: blog

        = link_to 'Back', blogs_path

app/views/blogs/show.html.erb
p
  #notice
    = notice

p
  strong Title:
  = blog.title

p
  strong Text:
  = blog.text %>

= link_to 'Edit', edit_blog_path(blog) |
= link_to 'Back', blogs_path

app/views/blogs/show.html.slim
- content_for :title, "#{blog.title}"

p
  #notice
    = notice

.medium-10.medium-centered.column
  .callout
    .blog
      .title
        .float-left
          h5 = blog.title
        .float-right
          = blog.created_at_h
      hr
      br
      p
        = raw blog.text

      h6.subheader.author.float-right
        | Author:
        '
        = link_to "#{blog.user.get_username} (@id#{blog.user.id})", profile_path(blog.user)
      br

      = render "links"

  .comment-form
    = render 'comments/form' if signed_in?

  .comments
    = render blog.comments

app/views/comments/_comment.html.slim
.comment.callout data-id=comment.id
  .title
    .author.float-left
      h5
        |
        = link_to comment.user.get_username, profile_path(comment.user)
        '
        - if comment.user.admin? || comment.user.editor?
          span#role style="color:red"
            = '•'

    .created_at_h.float-right
      = comment.created_at
  hr
  .body
    = comment.text
  .actions.float-right
    = link_to 'Delete', blog_comment_path(blog, comment), method: :delete, class:"tiny alert button" if signed_in? && (current_user == comment.user || current_user.admin? || current_user.editor?)
  .clearfix

app/views/comments/_form.html.slim
#comment-form
  = simple_form_for [blog, comment] do |f|
    f.error_notification

    .form-inputs
      = f.association :user, selected: current_user.id, input_html:{hidden:true}, label:false
      = f.association :blog, selected: blog.id, input_html:{hidden:true}, label:false
      = f.input :text, as: :text, label:'Your comment', placeholder:'Please, enter your comment here'

    .form-actions
      = f.button :submit, class:"button small button-success"
    .clearfix

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width initial-scale=1.0"

    title == content_for?(:title) ? "FS | #{yield(:title)}" : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css"
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css"
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.0/css/froala_editor.pkgd.min.css"
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.0/css/froala_style.min.css"

  body
    = render "application/navigation"
    .row
      == yield